"""
Django settings for editorial_project project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*(kw(f%vh8i0hstkegwki1mrl91au@qz&n)+#i-cq3d=i&b3$9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['134.122.31.117']
#ALLOWED_HOSTS = ['134.122.31.117', 'editorialproduccion.rqconsultores.net']
# Así es como debe quedar:
ALLOWED_HOSTS = ['134.122.31.117', 'editorialproduccion.rqconsultores.net', '127.0.0.1', 'localhost']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'produccion',  # <-- AGREGA ESTA LÍNEA
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'editorial_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'editorial_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'Personal', # La base de datos de nuestro proyecto
        'USER': 'sia',
        'PASSWORD': 'fuGvDyHxN9k8JyR',
        'HOST': '162.248.54.184',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
    'rq': {
        'ENGINE': 'mssql',
        'NAME': 'RQ', # La base de datos comercial
        'USER': 'rq',       # Puede ser el mismo usuario u otro
        'PASSWORD': 'fuGvDyHxN9k8JyR',  # Puede ser la misma u otra
        'HOST': '209.59.188.25,49156', # Probablemente el mismo host
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    }
}
#DATABASES = {
#    'default': {
#        'ENGINE': 'mssql',
#        'NAME': 'Personal', # <-- CAMBIA ESTO
#        'USER': 'sia',   # <-- CAMBIA ESTO
#        'PASSWORD': 'fuGvDyHxN9k8JyR', # <-- CAMBIA ESTO
#        'HOST': '162.248.54.184', # <-- CAMBIA ESTO (ej: 'localhost' o una IP)
#        'PORT': '1433', # El puerto por defecto de SQL Server
#
#        'OPTIONS': {
#            'driver': 'ODBC Driver 17 for SQL Server',
#        },
#    }
#}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATABASE_ROUTERS = ['produccion.routers.RQRouter']
