# Generated by Django 5.0.14 on 2025-06-16 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_libro', models.CharField(default='HP Escritora "A"', max_length=255)),
                ('temporada_anio', models.IntegerField(default=2025)),
                ('tiraje', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(default=400)),
                ('elaborado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('revisado_por', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fecha', models.DateField(default='2025-05-13')),
                ('producto_a_elaborar', models.CharField(default='Escribamos 4', max_length=255)),
                ('cantidad_a_producir', models.IntegerField(default=6800)),
                ('cantidad_hojas_por_ejemplar', models.IntegerField(default=38)),
                ('tiraje_total', models.IntegerField(default=131525)),
                ('numero_de_resmas', models.CharField(default='65 resmas + 3814', max_length=100)),
                ('medida_de_corte', models.CharField(default='20x15', max_length=100)),
                ('tamano', models.CharField(default='30x40', max_length=100)),
                ('papel', models.CharField(default='bond', max_length=100)),
                ('base', models.CharField(default='20', max_length=100)),
                ('total_planchas', models.IntegerField(default=104)),
                ('numero_de_pliegos', models.IntegerField(default=20)),
                ('medida_de_plancha', models.CharField(default='MO 630x530 Milimetros', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RequisicionEncabezado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_requisicion', models.IntegerField(unique=True)),
                ('producto_a_elaborar', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('solicitado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('autorizado_por', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControlProcesoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default='2025-10-15')),
                ('turno', models.IntegerField(default=2)),
                ('compaginado', models.IntegerField(blank=True, null=True)),
                ('doblado_libro', models.IntegerField(blank=True, null=True)),
                ('doblado_portada', models.IntegerField(blank=True, null=True)),
                ('engrapado', models.IntegerField(blank=True, null=True)),
                ('pegado', models.IntegerField(blank=True, null=True)),
                ('refilado', models.IntegerField(blank=True, null=True)),
                ('empacado', models.IntegerField(blank=True, null=True)),
                ('unidades', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('control_proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='produccion.controlproceso')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProduccionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montaje', models.CharField(default='152 C oldfon 150 3', max_length=100)),
                ('color', models.CharField(default='full', max_length=50)),
                ('impresion_full', models.BooleanField(default=False)),
                ('impresion_t', models.BooleanField(default=False)),
                ('impresion_r', models.BooleanField(default=True)),
                ('operario', models.CharField(blank=True, max_length=100, null=True)),
                ('maquina', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('total_impresion_programado', models.IntegerField(blank=True, null=True)),
                ('total_impresion_real', models.IntegerField(blank=True, null=True)),
                ('orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='produccion.ordenproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='RequisicionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_solicitado', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.requisicionencabezado')),
            ],
        ),
    ]
