# Generated by Django 5.0.14 on 2025-06-18 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorteDeBobina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reporte', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateField()),
                ('nombre_operario', models.CharField(max_length=255)),
                ('ancho_bobina', models.CharField(blank=True, max_length=50, null=True)),
                ('medida_de_corte', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotaIngresoProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateField()),
                ('elaborado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('recibido_por', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteDiarioProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_encargado', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('turno', models.CharField(max_length=50)),
                ('elaborado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('revisado_por', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='controlproceso',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controlproceso',
            name='nombre_del_libro',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='controlproceso',
            name='temporada_anio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='controlproceso',
            name='tiraje',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controlprocesodetalle',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='controlprocesodetalle',
            name='turno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='base',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='cantidad_a_producir',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='cantidad_hojas_por_ejemplar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='medida_de_corte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='medida_de_plancha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='numero_de_pliegos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='numero_de_resmas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='papel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='producto_a_elaborar',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='tamano',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='tiraje_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='total_planchas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenproducciondetalle',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenproducciondetalle',
            name='impresion_r',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordenproducciondetalle',
            name='montaje',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requisiciondetalle',
            name='requisicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='produccion.requisicionencabezado'),
        ),
        migrations.CreateModel(
            name='CorteDeBobinaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_bobina', models.CharField(max_length=100)),
                ('pliegos', models.IntegerField()),
                ('resmas', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('corte_de_bobina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='produccion.cortedebobina')),
            ],
        ),
        migrations.CreateModel(
            name='NotaIngresoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('descripcion_producto', models.CharField(max_length=255)),
                ('paquetes', models.CharField(blank=True, max_length=100, null=True)),
                ('unidades', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('nota_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='produccion.notaingresoproductoterminado')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteDiarioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255)),
                ('compaginado', models.IntegerField(blank=True, null=True)),
                ('doblado_libro', models.IntegerField(blank=True, null=True)),
                ('doblado_portada', models.IntegerField(blank=True, null=True)),
                ('engrapado', models.IntegerField(blank=True, null=True)),
                ('empacado', models.IntegerField(blank=True, null=True)),
                ('reporte_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='produccion.reportediarioproductoterminado')),
            ],
        ),
    ]
