# Generated by Django 5.0.14 on 2025-08-16 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_cortedebobina_notaingresoproductoterminado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('orden', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('idsucursal', models.IntegerField()),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('producto', models.ForeignKey(db_column='regi_orden', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='produccion.producto')),
                ('codigo', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('documento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento de Referencia')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('entrada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idsucursal', models.IntegerField()),
            ],
            options={
                'db_table': 'kardex',
                'managed': False,
            },
        ),
    ]
