# Generated by Django 5.0.14 on 2025-08-17 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_producto_kardex'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlproceso',
            name='orden_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles', to='produccion.ordenproduccion'),
        ),
        migrations.AddField(
            model_name='cortedebobina',
            name='orden_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cortes', to='produccion.ordenproduccion'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('DETENIDO', 'Detenido')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='requisicionencabezado',
            name='orden_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones', to='produccion.ordenproduccion'),
        ),
    ]
