# Generated by Django 5.0.14 on 2025-08-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_controlproceso_orden_produccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cortedebobinadetalle',
            name='codigo_bobina',
        ),
        migrations.RemoveField(
            model_name='cortedebobinadetalle',
            name='pliegos',
        ),
        migrations.AddField(
            model_name='cortedebobinadetalle',
            name='cantidad_pliegos_1',
            field=models.IntegerField(default=0, verbose_name='Cantidad Pliegos 1'),
        ),
        migrations.AddField(
            model_name='cortedebobinadetalle',
            name='cantidad_pliegos_2',
            field=models.IntegerField(default=0, verbose_name='Cantidad Pliegos 2'),
        ),
        migrations.AddField(
            model_name='cortedebobinadetalle',
            name='codigo_bobina_usada',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cortedebobinadetalle',
            name='codigo_pliego_producido_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Pliego Producido 1'),
        ),
        migrations.AddField(
            model_name='cortedebobinadetalle',
            name='codigo_pliego_producido_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Pliego Producido 2'),
        ),
        migrations.AlterField(
            model_name='cortedebobinadetalle',
            name='resmas',
            field=models.IntegerField(default=0),
        ),
    ]
