# Generated by Django 5.0.14 on 2025-08-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_remove_cortedebobinadetalle_codigo_bobina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cortedebobinadetalle',
            name='resmas',
        ),
        migrations.AddField(
            model_name='cortedebobinadetalle',
            name='resmas_producidas_1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Resmas Producidas 1'),
        ),
        migrations.AddField(
            model_name='cortedebobinadetalle',
            name='resmas_producidas_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Resmas Producidas 2'),
        ),
        migrations.AlterField(
            model_name='cortedebobinadetalle',
            name='codigo_bobina_usada',
            field=models.CharField(max_length=50, verbose_name='Bobina Usada'),
        ),
        migrations.AlterField(
            model_name='cortedebobinadetalle',
            name='codigo_pliego_producido_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pliego Producido 1'),
        ),
        migrations.AlterField(
            model_name='cortedebobinadetalle',
            name='codigo_pliego_producido_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pliego Producido 2'),
        ),
    ]
