# Generated by Django 5.0.14 on 2025-08-31 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0006_remove_cortedebobinadetalle_resmas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kardex',
            options={'ordering': ['-fecha'], 'verbose_name': 'Movimiento de Kardex', 'verbose_name_plural': 'Movimientos de Kardex'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
