# Generated by Django 5.0.14 on 2025-08-31 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0007_alter_kardex_options_alter_producto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kardex',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
    ]
