# Generated by Django 5.0.14 on 2025-10-21 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0008_alter_kardex_options_alter_producto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('nombrecomercial', models.CharField(blank=True, max_length=255, null=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consignacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cliente', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='produccion.cliente')),
            ],
            options={
                'verbose_name': 'Consignación',
                'verbose_name_plural': 'Consignaciones',
            },
        ),
        migrations.CreateModel(
            name='ConsignacionDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_linea', models.DecimalField(decimal_places=2, max_digits=12)),
                ('consignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='produccion.consignacion')),
                ('producto', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='produccion.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Consignación',
                'verbose_name_plural': 'Detalles de Consignación',
            },
        ),
    ]
