# Generated by Django 5.0.14 on 2025-10-26 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0009_cliente_consignacion_consignaciondetalle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consignacion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='consignaciondetalle',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='consignaciondetalle',
            name='consignacion',
            field=models.ForeignKey(db_column='consignacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='produccion.consignacion'),
        ),
        migrations.AlterField(
            model_name='consignaciondetalle',
            name='producto',
            field=models.ForeignKey(db_column='producto_id', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='produccion.producto'),
        ),
        migrations.AlterModelTable(
            name='consignaciondetalle',
            table='produccion_consignaciondetalle',
        ),
    ]
