# Generated by Django 5.0.14 on 2025-10-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0010_alter_consignacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consignaciondetalle',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='consignacion',
            table='produccion_consignacion',
        ),
    ]
