# Generated by Django 5.0.14 on 2025-11-15 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0011_alter_consignaciondetalle_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.CharField(max_length=50)),
                ('consignacion_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'produccion_liquidacion',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LiquidacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignacion_detalle_id', models.IntegerField(blank=True, null=True)),
                ('producto_id', models.IntegerField()),
                ('cantidad_consignada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_devuelta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_vendida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_linea', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='produccion.liquidacion')),
            ],
            options={
                'db_table': 'produccion_liquidaciondetalle',
            },
        ),
    ]
